/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CoffeeShop.order;

import CoffeeShop.LogInMenu;
import CoffeeShop.CoffeeShopSystem;
import CoffeeShop.Product;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Calendar;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.List;

/**
 * @author wangzhitao
 */
public class BuyAndReceipts extends javax.swing.JFrame {
    double[] drink = new double[5];
    double[] cake = new double[5];
    String[] cost = new String[3];
    double[] i = new double[10];
    double[] sum = new double[5];
    String receipt = "";

    /**
     * Creates new form BuyAndReceipts
     */
    public BuyAndReceipts() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    public void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlblTax = new javax.swing.JLabel();
        jlblSubTotal = new javax.swing.JLabel();
        jlblTotal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jChkCappuccino = new javax.swing.JCheckBox();
        jChkIcedCap = new javax.swing.JCheckBox();
        jChkEspresso = new javax.swing.JCheckBox();
        jChkLattle = new javax.swing.JCheckBox();
        jChkIcedLattle = new javax.swing.JCheckBox();
        jtxtCappuccino = new javax.swing.JTextField();
        jtxtIcedCap = new javax.swing.JTextField();
        jtxtEspresso = new javax.swing.JTextField();
        jtxtLattle = new javax.swing.JTextField();
        jtxtIcedLattle = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jChkCoffeeCake = new javax.swing.JCheckBox();
        jChkRedVelvet = new javax.swing.JCheckBox();
        jChkBoston = new javax.swing.JCheckBox();
        jChkBlack = new javax.swing.JCheckBox();
        jChkLagos = new javax.swing.JCheckBox();
        jtxtCoffeeCake = new javax.swing.JTextField();
        jtxtRedVelvet = new javax.swing.JTextField();
        jtxtBoston = new javax.swing.JTextField();
        jtxtBlack = new javax.swing.JTextField();
        jtxtLagos = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jBtnTotal = new javax.swing.JButton();
        jBtnReset = new javax.swing.JButton();
        jBtnReceipt = new javax.swing.JButton();
        jBtnExit = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtReceipt = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlblCostDrinks = new javax.swing.JLabel();
        jlblCostCakes = new javax.swing.JLabel();
        jlblService = new javax.swing.JLabel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setSize(1000, 600);
        this.setLocationRelativeTo(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel3.setText("Tax");

        jLabel4.setText("Sub Total");

        jLabel5.setText("Total");

        jlblTax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTax.setText("0");
        jlblTax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jlblSubTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblSubTotal.setText("0");
        jlblSubTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jlblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTotal.setText("0");
        jlblTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                .addGap(176, 176, 176)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlblTax, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                        .addComponent(jlblSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jlblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jlblTax, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(jLabel4))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jlblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jlblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(56, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 440, 180));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel1.setText("Cafe Management System");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(298, 298, 298)
                                .addComponent(jLabel1)
                                .addContainerGap(309, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1040, 70));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jChkCappuccino.setText("Cappuccino ¥2.0");
        jChkCappuccino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkCappuccinoMouseClicked(evt);
            }
        });
        jChkCappuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkCappuccinoActionPerformed(evt);
            }
        });

        jChkIcedCap.setText("Iced Cappuccino ¥1.0");
        jChkIcedCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkIcedCapMouseClicked(evt);
            }
        });
        jChkIcedCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkIcedCapActionPerformed(evt);
            }
        });

        jChkEspresso.setText("Espresso ¥2.5");
        jChkEspresso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkEspressoMouseClicked(evt);
            }
        });
        jChkEspresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkEspressoActionPerformed(evt);
            }
        });

        jChkLattle.setText("Latte");
        jChkLattle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkLattleMouseClicked(evt);
            }
        });
        jChkLattle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkLattleActionPerformed(evt);
            }
        });

        jChkIcedLattle.setText("Iced Latte");
        jChkIcedLattle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkIcedLattleMouseClicked(evt);
            }
        });
        jChkIcedLattle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkIcedLattleActionPerformed(evt);
            }
        });

        jtxtCappuccino.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jtxtCappuccino.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCappuccino.setText("0");
        jtxtCappuccino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtCappuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCappuccinoActionPerformed(evt);
            }
        });
        jtxtCappuccino.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                if (jtxtCappuccino.getText().equals("0"))
                    jtxtCappuccino.setText("");
            }
        });

        jtxtIcedCap.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jtxtIcedCap.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtIcedCap.setText("0");
        jtxtIcedCap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtIcedCap.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                if (jtxtIcedCap.getText().equals("0"))
                    jtxtIcedCap.setText("");
            }
        });

        jtxtEspresso.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jtxtEspresso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtEspresso.setText("0");
        jtxtEspresso.setToolTipText("");
        jtxtEspresso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtEspresso.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                if (jtxtEspresso.getText().equals("0"))
                    jtxtEspresso.setText("");
            }
        });
        jtxtLattle.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jtxtLattle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtLattle.setText("0");
        jtxtLattle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtLattle.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                if (jtxtLattle.getText().equals("0"))
                    jtxtLattle.setText("");
            }
        });
        jtxtIcedLattle.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jtxtIcedLattle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtIcedLattle.setText("0");
        jtxtIcedLattle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtIcedLattle.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                if (jtxtIcedLattle.getText().equals("0"))
                    jtxtIcedLattle.setText("");
            }
        });
        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jChkLattle)
                                                        .addComponent(jChkIcedLattle))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jtxtIcedLattle)
                                                        .addComponent(jtxtLattle, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jChkCappuccino)
                                                        .addComponent(jChkIcedCap)
                                                        .addComponent(jChkEspresso))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jtxtEspresso, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                                        .addComponent(jtxtIcedCap)
                                                        .addComponent(jtxtCappuccino))))
                                .addGap(34, 34, 34))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jChkCappuccino)
                                        .addComponent(jtxtCappuccino))
                                .addGap(11, 11, 11)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jChkIcedCap)
                                        .addComponent(jtxtIcedCap))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jChkEspresso)
                                        .addComponent(jtxtEspresso))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jChkLattle)
                                        .addComponent(jtxtLattle))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jChkIcedLattle)
                                        .addComponent(jtxtIcedLattle))
                                .addContainerGap(65, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 350, 260));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jChkCoffeeCake.setText("Coffee Cake");
        jChkCoffeeCake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkCoffeeCakeActionPerformed(evt);
            }
        });

        jChkRedVelvet.setText("Red Velvet Cake");
        jChkRedVelvet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkRedVelvetActionPerformed(evt);
            }
        });

        jChkBoston.setText("Boston Cream Pie");
        jChkBoston.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkBostonActionPerformed(evt);
            }
        });

        jChkBlack.setText("Black Forest Cake");
        jChkBlack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkBlackActionPerformed(evt);
            }
        });

        jChkLagos.setText("Lagos Chocolate Cake");
        jChkLagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkLagosActionPerformed(evt);
            }
        });

        jtxtCoffeeCake.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jtxtCoffeeCake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCoffeeCake.setText("0");
        jtxtCoffeeCake.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtCoffeeCake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCoffeeCakeActionPerformed(evt);
            }
        });
        jtxtCoffeeCake.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                if (jtxtCoffeeCake.getText().equals("0"))
                    jtxtCoffeeCake.setText("");
            }
        });
        jtxtRedVelvet.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jtxtRedVelvet.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtRedVelvet.setText("0");
        jtxtRedVelvet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtRedVelvet.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                if (jtxtRedVelvet.getText().equals("0"))
                    jtxtRedVelvet.setText("");
            }
        });
        jtxtBoston.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jtxtBoston.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtBoston.setText("0");
        jtxtBoston.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtBoston.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                if (jtxtBoston.getText().equals("0"))
                    jtxtBoston.setText("");
            }
        });
        jtxtBlack.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jtxtBlack.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtBlack.setText("0");
        jtxtBlack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtBlack.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                if (jtxtBlack.getText().equals("0"))
                    jtxtBlack.setText("");
            }
        });
        jtxtLagos.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jtxtLagos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtLagos.setText("0");
        jtxtLagos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtLagos.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                if (jtxtLagos.getText().equals("0"))
                    jtxtLagos.setText("");
            }
        });
        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jChkCoffeeCake)
                                        .addComponent(jChkRedVelvet)
                                        .addComponent(jChkBoston)
                                        .addComponent(jChkBlack)
                                        .addComponent(jChkLagos))
                                .addGap(5, 5, 5)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtxtLagos, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                        .addComponent(jtxtBlack)
                                        .addComponent(jtxtBoston)
                                        .addComponent(jtxtRedVelvet)
                                        .addComponent(jtxtCoffeeCake))
                                .addGap(28, 28, 28))
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jChkCoffeeCake)
                                        .addComponent(jtxtCoffeeCake))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jChkRedVelvet)
                                        .addComponent(jtxtRedVelvet))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jChkBoston)
                                        .addComponent(jtxtBoston))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jChkBlack)
                                        .addComponent(jtxtBlack))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jChkLagos)
                                        .addComponent(jtxtLagos))
                                .addContainerGap(56, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 330, 260));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jBtnTotal.setText("Total");
        jBtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTotalActionPerformed(evt);
            }
        });

        jBtnReset.setText("Rest");
        jBtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnResetActionPerformed(evt);
            }
        });

        jBtnReceipt.setText("Pay");
        jBtnReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayButtonActionPerformed(evt);
            }
        });

        jBtnExit.setText("Exit");
        jBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jBtnTotal)
                                        .addComponent(jBtnReceipt))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jBtnReset)
                                        .addComponent(jBtnExit))
                                .addGap(33, 33, 33))
        );
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jBtnReset)
                                        .addComponent(jBtnTotal))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jBtnReceipt)
                                        .addComponent(jBtnExit))
                                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 500, 310, 80));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jtxtReceipt.setColumns(20);
        jtxtReceipt.setRows(5);
        jScrollPane1.setViewportView(jtxtReceipt);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                                .addContainerGap())
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 320, 400));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel6.setText("Cost of Drinks");

        jLabel7.setText("Cost of Cakes");

        jLabel8.setText("Service Charge");
        jLabel8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel8KeyPressed(evt);
            }
        });

        jlblCostDrinks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblCostDrinks.setText("0");
        jlblCostDrinks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jlblCostCakes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblCostCakes.setText("0");
        jlblCostCakes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jlblService.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblService.setText("3.0");
        jlblService.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(18, 18, 18)
                                                .addComponent(jlblCostCakes, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(18, 18, 18)
                                                .addComponent(jlblCostDrinks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jlblService, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(22, 22, 22))
        );
        jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(jLabel6))
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jlblCostDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jlblCostCakes, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jlblService, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(97, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 250, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jChkIcedCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkIcedCapActionPerformed
        // TODO add your handling code here:
        double cIcedCap = Double.parseDouble(jlblCostDrinks.getText());
        double IcedCappuccino = Double.parseDouble(jtxtIcedCap.getText());
        double iIcedCappuccino = 1.0;

        if (jChkIcedCap.isSelected()) {
            i[1] = (IcedCappuccino * iIcedCappuccino) + cIcedCap;
            String pDrink = String.format("%.2f", i[1]);
            jlblCostDrinks.setText(pDrink);
            //jtxtIcedCap.setText(pDrink);

        }
    }//GEN-LAST:event_jChkIcedCapActionPerformed

    private void jChkIcedLattleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkIcedLattleActionPerformed
        // TODO add your handling code here:
        double cIcedLattle = Double.parseDouble(jlblCostDrinks.getText());
        double IcedLattle = Double.parseDouble(jtxtIcedLattle.getText());
        double iIcedLattle = 1.5;

        if (jChkIcedLattle.isSelected()) {
            i[4] = (IcedLattle * iIcedLattle) + cIcedLattle;
            String pDrink = String.format("%.2f", i[4]);
            jlblCostDrinks.setText(pDrink);
            //jtxtIcedLattle.setText(pDrink);

        }
    }//GEN-LAST:event_jChkIcedLattleActionPerformed

    private void jtxtCoffeeCakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCoffeeCakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCoffeeCakeActionPerformed

    private void jBtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnResetActionPerformed
        // TODO add your handling code here:
        jlblCostCakes.setText("0");
        jlblCostDrinks.setText("0");
        jlblService.setText("0");
        jlblTax.setText("0");
        jlblSubTotal.setText("0");
        jlblTotal.setText("0");
        jtxtCoffeeCake.setText("0");
        jtxtRedVelvet.setText("0");
        jtxtBoston.setText("0");
        jtxtBlack.setText("0");
        jtxtLagos.setText("0");
        jChkCappuccino.setSelected(false);
        jChkIcedCap.setSelected(false);
        jChkEspresso.setSelected(false);
        jChkLattle.setSelected(false);
        jChkIcedLattle.setSelected(false);
        jChkCoffeeCake.setSelected(false);
        jChkRedVelvet.setSelected(false);
        jChkBoston.setSelected(false);
        jChkBlack.setSelected(false);
        jChkLagos.setSelected(false);
        jtxtCappuccino.setText("0");
        jtxtIcedCap.setText("0");
        jtxtEspresso.setText("0");
        jtxtLattle.setText("0");
        jtxtIcedLattle.setText("0");
        jtxtReceipt.setText(null);
    }//GEN-LAST:event_jBtnResetActionPerformed

    private void jBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
//        new RegisterMenu().Page(CoffeeShopSystem.user.getRegistered(LogInMenu.name));
        new LogInMenu(CoffeeShopSystem.user);
    }//GEN-LAST:event_jBtnExitActionPerformed

    private void PayButtonActionPerformed(java.awt.event.ActionEvent evt) {
        //if there is no products has been selected
        if (jtxtReceipt.getText().equals("")) {

            JOptionPane.showMessageDialog(
                    this, "Please click Total first !",
                    "Notice",
                    JOptionPane.CLOSED_OPTION
            );
        } else {
            String total = jlblTotal.getText();
            int ok_cancel = 0;
            ImageIcon icon = new ImageIcon("src/CoffeeShop/images/qr.png");
            //if user is registered
            if (CoffeeShopSystem.isregister) {

                //user is vip
                if (CoffeeShopSystem.user.getRegistered(LogInMenu.name).isVipStatus()) {
                    float discount = CoffeeShopSystem.user.getRegistered(LogInMenu.name).getCard().getDiscount();
                    JComboBox jComboBox = new JComboBox();
                    jComboBox.addItem("VIP Discount(%5)");
                    jComboBox.addItem("Collecting Stamp");
                    jComboBox.setBounds(new Rectangle(200, 230, 200, 30));
                    ok_cancel = JOptionPane.showConfirmDialog(
                            this,
                            jComboBox,
                            "Please select Special offer:",
                            JOptionPane.OK_CANCEL_OPTION
                    );
                    String kind = jComboBox.getSelectedItem().toString();
                    if (kind.equals("Collecting Stamp")) {
                        CoffeeShopSystem.user.getRegistered(LogInMenu.name).getCard().addStamp();
                        JOptionPane.showConfirmDialog(
                                this,
                                "Collected 1 Stamp",
                                "Notice",
                                JOptionPane.CLOSED_OPTION
                        );
                    } else if (kind.equals("VIP Discount(%5)")) {
                        total = "" + ((double) Math.round(
                                (Double.parseDouble(
                                        total.substring(2)) * discount) * 100) / 100);
                    }
                } else {
                    //if user is not vip
                    JOptionPane.showConfirmDialog(
                            this,
                            "Collected 1 Stamp",
                            "Notice",
                            JOptionPane.CLOSED_OPTION
                    );
                    CoffeeShopSystem.user.getRegistered(LogInMenu.name).getCard().addStamp();
                }
                // user not cancel payment
                if (ok_cancel == 0) {
                    JOptionPane.showMessageDialog(
                            this,
                            "Please Scan QR code to pay \n" + total,
                            "Payment",
                            JOptionPane.CLOSED_OPTION,
                            icon
                    );

                    CoffeeShopSystem.user.getRegistered(LogInMenu.name).addOrder(receipt);

                    Product product = CoffeeShopSystem.product;
                    HashMap<String, List<Double>> map = product.getAllProducts();
                    List<Double> temp = map.get("Cappuccino");
                    temp.set(2, temp.get(2) + Double.parseDouble(jtxtCappuccino.getText().equals("") ? "0" : jtxtCappuccino.getText()));
                    temp.set(3, temp.get(3) + Double.parseDouble(jtxtCappuccino.getText().equals("") ? "0" : jtxtCappuccino.getText()));
                    map.put("Cappuccino", temp);
                    temp = map.get("Iced Cappuccino");
                    temp.set(2, temp.get(2) + Double.parseDouble(jtxtIcedCap.getText().equals("") ? "0" : jtxtIcedCap.getText()));
                    temp.set(3, temp.get(3) + Double.parseDouble(jtxtIcedCap.getText().equals("") ? "0" : jtxtIcedCap.getText()));
                    map.put("Iced Cappuccino", temp);
                    temp = map.get("Espresso");
                    temp.set(2, temp.get(2) + Double.parseDouble(jtxtEspresso.getText().equals("") ? "0" : jtxtEspresso.getText()));
                    temp.set(3, temp.get(3) + Double.parseDouble(jtxtEspresso.getText().equals("") ? "0" : jtxtEspresso.getText()));
                    map.put("Espresso", temp);
                    temp = map.get("Latte");
                    temp.set(2, temp.get(2) + Double.parseDouble(jtxtLattle.getText().equals("") ? "0" : jtxtLattle.getText()));
                    temp.set(3, temp.get(3) + Double.parseDouble(jtxtLattle.getText().equals("") ? "0" : jtxtLattle.getText()));
                    map.put("Latte", temp);
                    temp = map.get("Ice Latte");
                    temp.set(2, temp.get(2) + Double.parseDouble(jtxtIcedLattle.getText().equals("") ? "0" : jtxtIcedLattle.getText()));
                    temp.set(3, temp.get(3) + Double.parseDouble(jtxtIcedLattle.getText().equals("") ? "0" : jtxtIcedLattle.getText()));
                    map.put("Ice Latte", temp);
                    temp = map.get("Coffee Cake");
                    temp.set(2, temp.get(2) + Double.parseDouble(jtxtCoffeeCake.getText().equals("") ? "0" : jtxtCoffeeCake.getText()));
                    temp.set(3, temp.get(3) + Double.parseDouble(jtxtCoffeeCake.getText().equals("") ? "0" : jtxtCoffeeCake.getText()));
                    map.put("Coffee Cake", temp);
                    temp = map.get("Red Velvet");
                    temp.set(2, temp.get(2) + Double.parseDouble(jtxtRedVelvet.getText().equals("") ? "0" : jtxtRedVelvet.getText()));
                    temp.set(3, temp.get(3) + Double.parseDouble(jtxtRedVelvet.getText().equals("") ? "0" : jtxtRedVelvet.getText()));
                    map.put("Red Velvet", temp);
                    temp = map.get("Boston Cream Pie");
                    temp.set(2, temp.get(2) + Double.parseDouble(jtxtBoston.getText().equals("") ? "0" : jtxtBoston.getText()));
                    temp.set(3, temp.get(3) + Double.parseDouble(jtxtBoston.getText().equals("") ? "0" : jtxtBoston.getText()));
                    map.put("Boston Cream Pie", temp);
                    temp = map.get("Black forest Cake");
                    temp.set(2, temp.get(2) + Double.parseDouble(jtxtBlack.getText().equals("") ? "0" : jtxtBlack.getText()));
                    temp.set(3, temp.get(3) + Double.parseDouble(jtxtBlack.getText().equals("") ? "0" : jtxtBlack.getText()));
                    map.put("Black forest Cake", temp);
                    temp = map.get("Lagos Chocolate Cake");
                    temp.set(2, temp.get(2) + Double.parseDouble(jtxtLagos.getText().equals("") ? "0" : jtxtLagos.getText()));
                    temp.set(3, temp.get(3) + Double.parseDouble(jtxtLagos.getText().equals("") ? "0" : jtxtLagos.getText()));
                    map.put("Lagos Chocolate Cake", temp);
                }
            }
            else {
                JOptionPane.showMessageDialog(
                        this,
                        "Please Scan QR code to pay \n" + total,
                        "Payment",
                        JOptionPane.CLOSED_OPTION,
                        icon
                );
            }
        }
    }

    private void jBtnReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnReceiptActionPerformed
        // TODO add your handling code here:
        if (jtxtReceipt.getText().equals("")) {
            drink[0] = Double.parseDouble(jtxtCappuccino.getText().equals("") ? "0" : jtxtCappuccino.getText());
            drink[1] = Double.parseDouble(jtxtIcedCap.getText().equals("") ? "0" : jtxtIcedCap.getText());
            drink[2] = Double.parseDouble(jtxtEspresso.getText().equals("") ? "0" : jtxtEspresso.getText());
            drink[3] = Double.parseDouble(jtxtLattle.getText().equals("") ? "0" : jtxtLattle.getText());
            drink[4] = Double.parseDouble(jtxtIcedLattle.getText().equals("") ? "0" : jtxtIcedLattle.getText());
            cake[0] = Double.parseDouble(jtxtCoffeeCake.getText().equals("") ? "0" : jtxtCoffeeCake.getText());
            cake[1] = Double.parseDouble(jtxtRedVelvet.getText().equals("") ? "0" : jtxtRedVelvet.getText());
            cake[2] = Double.parseDouble(jtxtBoston.getText().equals("") ? "0" : jtxtBoston.getText());
            cake[3] = Double.parseDouble(jtxtBlack.getText().equals("") ? "0" : jtxtBlack.getText());
            cake[4] = Double.parseDouble(jtxtLagos.getText().equals("") ? "0" : jtxtLagos.getText());
            cost[0] = jlblTax.getText();
            cost[1] = jlblSubTotal.getText();
            cost[2] = jlblTotal.getText();

            int refs = 1325 + (int) (Math.random() * 4238);

            Calendar timer = Calendar.getInstance();
            timer.getTime();
            SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
            tTime.format(timer.getTime());
            SimpleDateFormat Tdate = new SimpleDateFormat("yyyy-MM-dd");
            Tdate.format(timer.getTime());
            receipt = "\t\n Cafe Management Systems:\n\n" +
                    "Reference:\t\t\t" + refs +
                    "\n===============================\t ";
            if (drink[0] != 0) receipt += "\nCappuccino:\t\t\t" + drink[0];
            if (drink[1] != 0) receipt += "\nIced Cappuccino:\t\t" + drink[1];
            if (drink[2] != 0) receipt += "\nEspresso:\t\t\t" + drink[2];
            if (drink[3] != 0) receipt += "\nLattle:\t\t\t" + drink[3];
            if (drink[4] != 0) receipt += "\nIced Lattle:\t\t\t" + drink[4];
            if (cake[0] != 0) receipt += "\nCoffee Cake:\t\t\t" + cake[0];
            if (cake[1] != 0) receipt += "\nRed Velvet Cake:\t\t" + cake[1];
            if (cake[2] != 0) receipt += "\nBoston Cream Pie:\t\t" + cake[2];
            if (cake[3] != 0) receipt += "\nBlack Forest Cake:\t\t" + cake[3];
            if (cake[4] != 0) receipt += "\nLagos Chocolate Cake:\t\t" + cake[4];
            receipt += "\n================================\t" +
                    "\nTax:\t\t\t" + cost[0] +
                    "\nSub Total:\t\t\t" + cost[1] +
                    "\nTotal:\t\t\t" + cost[2] + "\n================================\t" +
                    "\nDate: " + Tdate.format(timer.getTime()) +
                    "\tTime: " + tTime.format(timer.getTime());
//            System.out.println(jtxtReceipt.getText());

            jtxtReceipt.append(receipt);
        }
    }//GEN-LAST:event_jBtnReceiptActionPerformed

    private void jChkCappuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkCappuccinoActionPerformed
        // TODO add your handling code here:
        double cCap = Double.parseDouble(jlblCostDrinks.getText());
        double Cappuccino = Double.parseDouble(jtxtCappuccino.getText());
        double iCappuccino = 2.0;

        if (jChkCappuccino.isSelected()) {
            i[0] = (Cappuccino * iCappuccino) + cCap;
            String pDrink = String.format("%.2f", i[0]);
            jlblCostDrinks.setText(pDrink);
            //jtxtCappuccino.setText(pDrink);

        }
    }//GEN-LAST:event_jChkCappuccinoActionPerformed

    private void jChkCoffeeCakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkCoffeeCakeActionPerformed
        // TODO add your handling code here:
        double cCoffeeCake = Double.parseDouble(jlblCostCakes.getText());
        double CoffeeCake = Double.parseDouble(jtxtCoffeeCake.getText());
        double iCoffeeCake = 1.0;

        if (jChkCoffeeCake.isSelected()) {
            i[5] = (CoffeeCake * iCoffeeCake) + cCoffeeCake;
            String pCake = String.format("%.2f", i[5]);
            jlblCostCakes.setText(pCake);
            //jtxtLattle.setText(pDrink);

        }
    }//GEN-LAST:event_jChkCoffeeCakeActionPerformed

    private void jChkRedVelvetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkRedVelvetActionPerformed
        // TODO add your handling code here:
        double cRedVelvet = Double.parseDouble(jlblCostCakes.getText());
        double RedVelvet = Double.parseDouble(jtxtRedVelvet.getText());
        double iRedVelvet = 1.5;

        if (jChkRedVelvet.isSelected()) {
            i[6] = (RedVelvet * iRedVelvet) + cRedVelvet;
            String pCake = String.format("%.2f", i[6]);
            jlblCostCakes.setText(pCake);
            //jtxtLattle.setText(pDrink);

        }
    }//GEN-LAST:event_jChkRedVelvetActionPerformed

    private void jChkBostonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkBostonActionPerformed
        // TODO add your handling code here:
        double cBoston = Double.parseDouble(jlblCostCakes.getText());
        double Boston = Double.parseDouble(jtxtBoston.getText());
        double iBoston = 2.0;

        if (jChkBoston.isSelected()) {
            i[7] = (Boston * iBoston) + cBoston;
            String pCake = String.format("%.2f", i[7]);
            jlblCostCakes.setText(pCake);
            //jtxtLattle.setText(pDrink);

        }
    }//GEN-LAST:event_jChkBostonActionPerformed

    private void jChkBlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkBlackActionPerformed
        // TODO add your handling code here:
        double cBlack = Double.parseDouble(jlblCostCakes.getText());
        double Black = Double.parseDouble(jtxtBlack.getText());
        double iBlack = 2.5;

        if (jChkBlack.isSelected()) {
            i[8] = (Black * iBlack) + cBlack;
            String pCake = String.format("%.2f", i[8]);
            jlblCostCakes.setText(pCake);
            //jtxtLattle.setText(pDrink);

        }
    }//GEN-LAST:event_jChkBlackActionPerformed

    private void jChkLagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkLagosActionPerformed
        // TODO add your handling code here:
        double cLagos = Double.parseDouble(jlblCostCakes.getText());
        double Lagos = Double.parseDouble(jtxtLagos.getText());
        double iLagos = 3.0;

        if (jChkLagos.isSelected()) {
            i[9] = (Lagos * iLagos) + cLagos;
            String pCake = String.format("%.2f", i[9]);
            jlblCostCakes.setText(pCake);
            //jtxtLattle.setText(pDrink);

        }
    }//GEN-LAST:event_jChkLagosActionPerformed

    private void jChkEspressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkEspressoActionPerformed
        // TODO add your handling code here:
        double cEspresso = Double.parseDouble(jlblCostDrinks.getText());
        double Espresso = Double.parseDouble(jtxtEspresso.getText());
        double iEspresso = 2.5;

        if (jChkEspresso.isSelected()) {
            i[2] = (Espresso * iEspresso) + cEspresso;
            String pDrink = String.format("%.2f", i[2]);
            jlblCostDrinks.setText(pDrink);
            //jtxtEspresso.setText(pDrink);

        }
    }//GEN-LAST:event_jChkEspressoActionPerformed

    private void jChkLattleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkLattleActionPerformed
        // TODO add your handling code here:
        double cLattle = Double.parseDouble(jlblCostDrinks.getText());
        double Lattle = Double.parseDouble(jtxtLattle.getText());
        double iLattle = 3.0;

        if (jChkLattle.isSelected()) {
            i[3] = (Lattle * iLattle) + cLattle;
            String pDrink = String.format("%.2f", i[3]);
            jlblCostDrinks.setText(pDrink);
            //jtxtLattle.setText(pDrink);

        }
    }//GEN-LAST:event_jChkLattleActionPerformed

    private void jChkLattleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkLattleMouseClicked

    }//GEN-LAST:event_jChkLattleMouseClicked

    private void jChkCappuccinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkCappuccinoMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jChkCappuccinoMouseClicked

    private void jChkIcedCapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkIcedCapMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jChkIcedCapMouseClicked

    private void jChkIcedLattleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkIcedLattleMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jChkIcedLattleMouseClicked

    private void jChkEspressoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkEspressoMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jChkEspressoMouseClicked

    private void jLabel8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel8KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8KeyPressed

    private void jtxtCappuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCappuccinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCappuccinoActionPerformed

    private void jBtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTotalActionPerformed
        // TODO add your handling code here:

        sum[1] = Double.parseDouble(jlblCostDrinks.getText());
        sum[2] = Double.parseDouble(jlblCostCakes.getText());
        sum[3] = Double.parseDouble(jlblService.getText());

        double cTotal = (sum[1] + sum[2] + sum[3]);
        String iTaxTotal = String.format("$ %.2f", cTotal / 100);
        jlblTax.setText(iTaxTotal);

        double subTotal = (cTotal);
        String isubTotal = String.format("$ %.2f", subTotal);
        jlblSubTotal.setText(isubTotal);

        double allTotal = (cTotal);
        String iTotal = String.format("$ %.2f", allTotal + (allTotal / 100));
        jlblTotal.setText(iTotal);
        jBtnReceiptActionPerformed(evt);

    }//GEN-LAST:event_jBtnTotalActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(BuyAndReceipts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(BuyAndReceipts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(BuyAndReceipts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(BuyAndReceipts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new BuyAndReceipts().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnExit;
    private javax.swing.JButton jBtnReceipt;
    private javax.swing.JButton jBtnReset;
    private javax.swing.JButton jBtnTotal;
    private javax.swing.JCheckBox jChkBlack;
    private javax.swing.JCheckBox jChkBoston;
    private javax.swing.JCheckBox jChkCappuccino;
    private javax.swing.JCheckBox jChkCoffeeCake;
    private javax.swing.JCheckBox jChkEspresso;
    private javax.swing.JCheckBox jChkIcedCap;
    private javax.swing.JCheckBox jChkIcedLattle;
    private javax.swing.JCheckBox jChkLagos;
    private javax.swing.JCheckBox jChkLattle;
    private javax.swing.JCheckBox jChkRedVelvet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlblCostCakes;
    private javax.swing.JLabel jlblCostDrinks;
    private javax.swing.JLabel jlblService;
    private javax.swing.JLabel jlblSubTotal;
    private javax.swing.JLabel jlblTax;
    private javax.swing.JLabel jlblTotal;
    private javax.swing.JTextField jtxtBlack;
    private javax.swing.JTextField jtxtBoston;
    private javax.swing.JTextField jtxtCappuccino;
    private javax.swing.JTextField jtxtCoffeeCake;
    private javax.swing.JTextField jtxtEspresso;
    private javax.swing.JTextField jtxtIcedCap;
    private javax.swing.JTextField jtxtIcedLattle;
    private javax.swing.JTextField jtxtLagos;
    private javax.swing.JTextField jtxtLattle;
    private javax.swing.JTextArea jtxtReceipt;
    private javax.swing.JTextField jtxtRedVelvet;
    // End of variables declaration//GEN-END:variables
}
