/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CoffeeShop.order;

import CoffeeShop.CoffeeShopSystem;
import CoffeeShop.PrivateRoom;

import javax.swing.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 * @author xingy
 */
public class ViewRoomReservationPage extends javax.swing.JFrame {

    /**
     * Creates new form ViewRoomReservationPage
     */
    public ViewRoomReservationPage() {
        this.setSize(1000, 600);
        this.setLocationRelativeTo(null);
        initComponents();
    }

    PrivateRoom privateRoom = CoffeeShopSystem.privateRoom;
    List<List<String>> RoomList = privateRoom.getRoom();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ReservationList = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        NameText = new javax.swing.JTextField();
        MonthComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DataComboBox = new javax.swing.JComboBox<>();
        TimeComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        pmButton = new javax.swing.JRadioButton();
        amButton = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        NumberOfPeopleComboBox = new javax.swing.JComboBox<>();
        AimText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        BookButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel1.setFont(new java.awt.Font("Apple Chancery", 3, 36)); // NOI18N
        jLabel1.setText("Room Reservation");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(298, 298, 298)
                                .addComponent(jLabel1)
                                .addContainerGap(332, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ReservationList.setBorder(javax.swing.BorderFactory.createTitledBorder(
                javax.swing.BorderFactory.createLineBorder(
                        new java.awt.Color(0, 0, 0), 3),
                "Room Reservation List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        DefaultListModel dlm = new DefaultListModel();
        /**
         * @param room
         * 0: date
         * 1: name
         * 2: Peoplenumber
         * 3: duration
         * 4: phone
         */
        System.out.println(RoomList.get(0));
        for (int i = 0; i < RoomList.size(); i++) {
            SimpleDateFormat sf = new SimpleDateFormat("yyyy/MM/dd");
            String temp = "";
            temp += "Date:" + RoomList.get(i).get(0) + " | ";
            temp += "Name:" + RoomList.get(i).get(1) + " | ";
            temp += "People_Num:" + RoomList.get(i).get(2) + " | ";
            temp += "Duration:" + RoomList.get(i).get(3) + " | ";
            temp += "Phone:" + RoomList.get(i).get(4);
            dlm.add(i, temp);
        }
        ReservationList.setModel(dlm);

        jScrollPane1.setViewportView(ReservationList);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel3.setText("Name:");

        NameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTextActionPerformed(evt);
            }
        });

        MonthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"}));
        MonthComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonthComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setText("Months:");

        jLabel5.setText("Date:");

        DataComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31"}));

        TimeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"}));

        jLabel6.setText("Time:");

        buttonGroup1.add(pmButton);
        pmButton.setText("pm");

        buttonGroup1.add(amButton);
        amButton.setText("am");

        jLabel7.setText("Number Of People:");

        NumberOfPeopleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[]{"1", "2", "3", "4", "5", "6", "7", "8", "9", "10",
                "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"}));

        jLabel8.setText("Phone: ");

        BookButton.setBackground(new java.awt.Color(204, 204, 204));
        BookButton.setFont(new java.awt.Font("Apple Chancery", 3, 13)); // NOI18N
        BookButton.setText("Book");
        BookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    BookButtonActionPerformed(evt);
                } catch (ParseException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(amButton)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(pmButton))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel6)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(TimeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addContainerGap(159, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel5)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(DataComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jLabel3)
                                                                        .addComponent(jLabel4))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGap(6, 6, 6)
                                                                                .addComponent(MonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addComponent(NameText, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(63, 63, 63)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel7)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(NumberOfPeopleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel8)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(AimText, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(240, Short.MAX_VALUE))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(166, 166, 166)
                                                .addComponent(BookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(NameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7)
                                        .addComponent(NumberOfPeopleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(13, 13, 13)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel4)
                                                        .addComponent(MonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(DataComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel5)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(AimText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel8))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(TimeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6)
                                        .addComponent(BookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(amButton)
                                        .addComponent(pmButton))
                                .addGap(0, 6, Short.MAX_VALUE))
        );

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Apple Chancery", 3, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add Reservation");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        deleteButton.setBackground(new java.awt.Color(204, 204, 204));
        deleteButton.setFont(new java.awt.Font("Apple Chancery", 3, 13)); // NOI18N
        deleteButton.setText("delete");
        deleteButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(204, 204, 204));
        backButton.setFont(new java.awt.Font("Apple Chancery", 3, 13)); // NOI18N
        backButton.setText("back");
        backButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(685, 685, 685)
                                                                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(23, 23, 23)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addContainerGap())
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(202, 202, 202)
                                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTextActionPerformed

    private void MonthComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonthComboBoxActionPerformed
        String month= MonthComboBox.getSelectedItem().toString();

        if(month.equals("1")){
            String def[] = { "1", "2", "3", "4", "5", "6", "7","8","9","10","11","12","13","14","15","16", "17", "18", "19", "20", "21", "22","23","24","25","26","27","28" ,"29","30","31"};
            DefaultComboBoxModel comboBox = new DefaultComboBoxModel(def);
            DataComboBox.setModel(comboBox);
        }
        else if(month.equals("2")){
            String def[] = { "1", "2", "3", "4", "5", "6", "7","8","9","10","11","12","13","14","15","16", "17", "18", "19", "20", "21", "22","23","24","25","26","27","28" };
            DefaultComboBoxModel comboBox = new DefaultComboBoxModel(def);
            DataComboBox.setModel(comboBox);
        }
        else if(month.equals("3")){
            String def[] = { "1", "2", "3", "4", "5", "6", "7","8","9","10","11","12","13","14","15","16", "17", "18", "19", "20", "21", "22","23","24","25","26","27","28","29","30","31" };
            DefaultComboBoxModel comboBox = new DefaultComboBoxModel(def);
            DataComboBox.setModel(comboBox);
        }
        else if(month.equals("4")){
            String def[] = { "1", "2", "3", "4", "5", "6", "7","8","9","10","11","12","13","14","15","16", "17", "18", "19", "20", "21", "22","23","24","25","26","27","28" ,"29","30"};
            DefaultComboBoxModel comboBox = new DefaultComboBoxModel(def);
            DataComboBox.setModel(comboBox);
        }
        else if(month.equals("5")){
            String def[] = { "1", "2", "3", "4", "5", "6", "7","8","9","10","11","12","13","14","15","16", "17", "18", "19", "20", "21", "22","23","24","25","26","27","28","29","30","31" };
            DefaultComboBoxModel comboBox = new DefaultComboBoxModel(def);
            DataComboBox.setModel(comboBox);
        }
        else if(month.equals("6")){
            String def[] = { "1", "2", "3", "4", "5", "6", "7","8","9","10","11","12","13","14","15","16", "17", "18", "19", "20", "21", "22","23","24","25","26","27","28" ,"29","30"};
            DefaultComboBoxModel comboBox = new DefaultComboBoxModel(def);
            DataComboBox.setModel(comboBox);
        }
        else if(month.equals("7")){
            String def[] = { "1", "2", "3", "4", "5", "6", "7","8","9","10","11","12","13","14","15","16", "17", "18", "19", "20", "21", "22","23","24","25","26","27","28" ,"29","30","31"};
            DefaultComboBoxModel comboBox = new DefaultComboBoxModel(def);
            DataComboBox.setModel(comboBox);
        }
        else if(month.equals("8")){
            String def[] = { "1", "2", "3", "4", "5", "6", "7","8","9","10","11","12","13","14","15","16", "17", "18", "19", "20", "21", "22","23","24","25","26","27","28","29","30","31" };
            DefaultComboBoxModel comboBox = new DefaultComboBoxModel(def);
            DataComboBox.setModel(comboBox);
        }
        else if(month.equals("9")){
            String def[] = { "1", "2", "3", "4", "5", "6", "7","8","9","10","11","12","13","14","15","16", "17", "18", "19", "20", "21", "22","23","24","25","26","27","28","29","30" };
            DefaultComboBoxModel comboBox = new DefaultComboBoxModel(def);
            DataComboBox.setModel(comboBox);
        }
        else if(month.equals("10")){
            String def[] = { "1", "2", "3", "4", "5", "6", "7","8","9","10","11","12","13","14","15","16", "17", "18", "19", "20", "21", "22","23","24","25","26","27","28","29","30","31" };
            DefaultComboBoxModel comboBox = new DefaultComboBoxModel(def);
            DataComboBox.setModel(comboBox);
        }
        else if(month.equals("11")){
            String def[] = { "1", "2", "3", "4", "5", "6", "7","8","9","10","11","12","13","14","15","16", "17", "18", "19", "20", "21", "22","23","24","25","26","27","28","29","30" };
            DefaultComboBoxModel comboBox = new DefaultComboBoxModel(def);
            DataComboBox.setModel(comboBox);
        }
        else if(month.equals("12")){
            String def[] = { "1", "2", "3", "4", "5", "6", "7","8","9","10","11","12","13","14","15","16", "17", "18", "19", "20", "21", "22","23","24","25","26","27","28","29","30","31" };
            DefaultComboBoxModel comboBox = new DefaultComboBoxModel(def);
            DataComboBox.setModel(comboBox);
        }
    }//GEN-LAST:event_MonthComboBoxActionPerformed

    private void BookButtonActionPerformed(java.awt.event.ActionEvent evt) throws ParseException {//GEN-FIRST:event_BookButtonActionPerformed
        String name = NameText.getText();
        String month = MonthComboBox.getEditor().getItem().toString();
        String data = DataComboBox.getEditor().getItem().toString();
        String Time = TimeComboBox.getEditor().getItem().toString();
        boolean AM = amButton.isSelected();
        String NumOfPeople = NumberOfPeopleComboBox.getEditor().getItem().toString();
        String aim = AimText.getText();

        DefaultListModel dlm = new DefaultListModel();
        for (int i = 0; i < ReservationList.getModel().getSize(); i++) {
            String ele = ReservationList.getModel().getElementAt(i);
            dlm.add(i, ele);
        }
        int size = dlm.getSize();
        if (!AM) Time = String.valueOf(Integer.parseInt(Time) + 12);
        if (Integer.parseInt(month) < 10) month = "0" + month;
        if (Integer.parseInt(data) < 10) data = "0" + data;

        dlm.add(size, "Date: 2022/"+ month +"/" + data +" | Name: " + name  + " | People_Num:"
                + NumOfPeople + " | Duration: " + Time + ":00" + "" + " | Phone: " + aim);
        ReservationList.setModel(dlm);
        amButton.setSelected(false);
        pmButton.setSelected(false);
        MonthComboBox.setSelectedIndex(-1);
        DataComboBox.setSelectedIndex(-1);
        TimeComboBox.setSelectedIndex(-1);
        NumberOfPeopleComboBox.setSelectedIndex(-1);
        AimText.setText("");
        NameText.setText("");

        Date date = new SimpleDateFormat("yyyy/MM/dd").parse(String.format("2022/%s/%s",month,data));
        PrivateRoom room = new PrivateRoom(date, name, NumOfPeople, Time+":00","null");
        privateRoom.addReservation(room);
    }//GEN-LAST:event_BookButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed

        String deleteUser = ReservationList.getSelectedValue();
        DefaultListModel dlm = new DefaultListModel();
        int index = -1;
        String[] list = deleteUser.split(" \\| ");
        System.out.println(Arrays.toString(list));
        for (int i = 0; i < ReservationList.getModel().getSize(); i++) {
            String ele = ReservationList.getModel().getElementAt(i);
            dlm.add(i, ele);
            if (ele.equals(deleteUser)) index = i;
        }
        if (index != -1) {
            dlm.remove(index);
            privateRoom.deleteReservation(list);
            System.out.println(privateRoom.getRoom());
        }
        ReservationList.setModel(dlm);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
//        this.setVisible(false);
        this.dispose();
        new AdminManagementSystem().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewRoomReservationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewRoomReservationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewRoomReservationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewRoomReservationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewRoomReservationPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AimText;
    private javax.swing.JButton BookButton;
    private javax.swing.JComboBox<String> DataComboBox;
    private javax.swing.JComboBox<String> MonthComboBox;
    private javax.swing.JTextField NameText;
    private javax.swing.JComboBox<String> NumberOfPeopleComboBox;
    private javax.swing.JList<String> ReservationList;
    private javax.swing.JComboBox<String> TimeComboBox;
    private javax.swing.JRadioButton amButton;
    private javax.swing.JButton backButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton pmButton;
    // End of variables declaration//GEN-END:variables
}
